const SYSTEM_EVENTS = {
  // Workflow Events
  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_APPROVED: 'WORKFLOW_APPROVED', // Overall completion
  WORKFLOW_REJECTED: 'WORKFLOW_REJECTED',
  WORKFLOW_STAGE_APPROVED: 'WORKFLOW_STAGE_APPROVED',
  WORKFLOW_ESCALATED: 'WORKFLOW_ESCALATED',

  // SLA Events
  SLA_WARNING: 'SLA_WARNING',
  SLA_BREACHED: 'SLA_BREACHED',

  // Procurement Entity Events (Future proofing)
  PR_CREATED: 'PR_CREATED',
  PR_APPROVED: 'PR_APPROVED',
  RFQ_CREATED: 'RFQ_CREATED',
  QUOTE_SELECTED: 'QUOTE_SELECTED',

  // Scheduled Events
  SCHEDULED_TRIGGER: 'SCHEDULED_TRIGGER',
  SCHEDULE_STARTED: 'SCHEDULE_STARTED',
  SCHEDULE_COMPLETED: 'SCHEDULE_COMPLETED'
};

module.exports = SYSTEM_EVENTS;
